/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPortfolioStackRouteImport } from './routes/api/portfolio/stack'
import { Route as ApiPortfolioProjectsRouteImport } from './routes/api/portfolio/projects'
import { Route as ApiPortfolioExperienceRouteImport } from './routes/api/portfolio/experience'

const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioStackRoute = ApiPortfolioStackRouteImport.update({
  id: '/api/portfolio/stack',
  path: '/api/portfolio/stack',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioProjectsRoute = ApiPortfolioProjectsRouteImport.update({
  id: '/api/portfolio/projects',
  path: '/api/portfolio/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortfolioExperienceRoute = ApiPortfolioExperienceRouteImport.update({
  id: '/api/portfolio/experience',
  path: '/api/portfolio/experience',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/api/portfolio/experience': typeof ApiPortfolioExperienceRoute
  '/api/portfolio/projects': typeof ApiPortfolioProjectsRoute
  '/api/portfolio/stack': typeof ApiPortfolioStackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/api/portfolio/experience': typeof ApiPortfolioExperienceRoute
  '/api/portfolio/projects': typeof ApiPortfolioProjectsRoute
  '/api/portfolio/stack': typeof ApiPortfolioStackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/projects': typeof ProjectsRoute
  '/api/portfolio/experience': typeof ApiPortfolioExperienceRoute
  '/api/portfolio/projects': typeof ApiPortfolioProjectsRoute
  '/api/portfolio/stack': typeof ApiPortfolioStackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/projects'
    | '/api/portfolio/experience'
    | '/api/portfolio/projects'
    | '/api/portfolio/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/projects'
    | '/api/portfolio/experience'
    | '/api/portfolio/projects'
    | '/api/portfolio/stack'
  id:
    | '__root__'
    | '/'
    | '/projects'
    | '/api/portfolio/experience'
    | '/api/portfolio/projects'
    | '/api/portfolio/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProjectsRoute: typeof ProjectsRoute
  ApiPortfolioExperienceRoute: typeof ApiPortfolioExperienceRoute
  ApiPortfolioProjectsRoute: typeof ApiPortfolioProjectsRoute
  ApiPortfolioStackRoute: typeof ApiPortfolioStackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/stack': {
      id: '/api/portfolio/stack'
      path: '/api/portfolio/stack'
      fullPath: '/api/portfolio/stack'
      preLoaderRoute: typeof ApiPortfolioStackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/projects': {
      id: '/api/portfolio/projects'
      path: '/api/portfolio/projects'
      fullPath: '/api/portfolio/projects'
      preLoaderRoute: typeof ApiPortfolioProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portfolio/experience': {
      id: '/api/portfolio/experience'
      path: '/api/portfolio/experience'
      fullPath: '/api/portfolio/experience'
      preLoaderRoute: typeof ApiPortfolioExperienceRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProjectsRoute: ProjectsRoute,
  ApiPortfolioExperienceRoute: ApiPortfolioExperienceRoute,
  ApiPortfolioProjectsRoute: ApiPortfolioProjectsRoute,
  ApiPortfolioStackRoute: ApiPortfolioStackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
